# Generated by Django 3.2.7 on 2021-09-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passengers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=10)),
                ('last', models.CharField(max_length=10)),
                ('flight', models.ManyToManyField(blank=True, related_name='passenger', to='flights.Flight')),
            ],
        ),
        migrations.DeleteModel(
            name='Passengers',
        ),
    ]
